//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Server.PenteServer.PenteServer"/> </summary
    public sealed class PenteServerClient : Beamable.Server.MicroserviceClient
    {
        
        /// <summary>
        /// Call the NewGame method on the PenteServer microservice
        /// <see cref="Beamable.Server.PenteServer.PenteServer.NewGame"/>
        /// </summary>
        public Beamable.Common.Promise<Pente.Core.StartGameResponse> NewGame()
        {
            string[] serializedFields = new string[0];
            return this.Request<Pente.Core.StartGameResponse>("PenteServer", "NewGame", serializedFields);
        }
        
        /// <summary>
        /// Call the SubmitMove method on the PenteServer microservice
        /// <see cref="Beamable.Server.PenteServer.PenteServer.SubmitMove"/>
        /// </summary>
        public Beamable.Common.Promise<Pente.Core.SubmitMoveResponse> SubmitMove(Pente.Core.SubmitMoveRequest req)
        {
            string serialized_req = this.SerializeArgument<Pente.Core.SubmitMoveRequest>(req);
            string[] serializedFields = new string[] {
                    serialized_req};
            return this.Request<Pente.Core.SubmitMoveResponse>("PenteServer", "SubmitMove", serializedFields);
        }
    }
}
